# name: Github action ofr
# on: 
#  push:
#     branches: [master]
# jobs: 
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Print Hello World
#       run: node --version

name: Print Node Version
on: push
jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Print Node Version
        run: node -v